### ISSUE TITLE
Indentation errors and missing module(s)

### ISSUE THREAD

**Issue by rejhgadellaa** [shantanu561993/PyImageOptimiser#3]
I installed PyImageOptimiser via pip 

```
pip3 install PyImageOptimiser
```

When I tried to use it I first got indentation errors (starting at line 29). Those were fixed easily enough but now I get:

```
Traceback (most recent call last):
  File "optimizer.py", line 44, in <module>
    import PyImageOptimizer
  File "c:\python35\lib\site-packages\PyImageOptimizer\__init__.py", line 7, in <module>
    from .PyImageOptimizer import optimize_jpg,optimize_png,optimize
  File "c:\python35\lib\site-packages\PyImageOptimizer\PyImageOptimizer.py", line 6, in <module>
    import requests
ImportError: No module named 'requests'
```

Windows 10, x64

**Comment by rejhgadellaa** [comment]
Okay my bad I hadn't installed the requests module.

```
pip3 install requests
```

Did I miss this when I looked at Installation docs?

Still, the indentation errors need fixing.

**Comment by shantanu561993** [comment]
If you used pip , I cant see a reason why pip didn't install requests , its already specified in requirements.txt 

Can you point out the wrong indentation . I'll be happy to fix .. :)

**Comment by rejhgadellaa** [comment]
Hmm I had some issues with installing with easy_install at first so maybe that's related? I'll give it a try on another computer, see what happens there. Maybe something weird is going on on my machine? Would also explain the indent errors. Maybe. :P

Anyways. I fixed the indent errors so I'm not entirely sure where they were but it started at line 29 and in PyImageOptimiser.py

The next block also had some issues (with the for loop in the for loop).

I'll report back when I checked it on another machine, may take until sunday because I have kind of a busy schedule the coming days.

Thanks for the quick reply btw!

**Comment by shantanu561993** [comment]
Thanks .. @rejhgadellaa  I'll be happy to fix . I tried on my system though , it worked flawlessly.

**Comment by rejhgadellaa** [comment]
Okay just tried it on another machine and paid attention while installing. I got this:

```
C:\Python34\Scripts>pip3 install PyImageOptimizer
Downloading/unpacking PyImageOptimizer
  Downloading PyImageOptimizer-1.0.tar.gz
  Running setup.py (path:C:\Users\PDADDY~1\AppData\Local\Temp\pip_build_P Daddy\PyImageOptimizer\setup.py) egg_info for package PyImageOptimizer

Installing collected packages: PyImageOptimizer
  Running setup.py install for PyImageOptimizer
    Sorry: TabError: inconsistent use of tabs and spaces in indentation (PyImageOptimizer.py, line 29)

Successfully installed PyImageOptimizer
Cleaning up...
```

Windows 7, x64 python34

**Comment by rejhgadellaa** [comment]
Looks like a "convert tab indentation" in Scite did the trick. So I'm guessing the file contains tabs and spaces for indentation (and especially tabsize can be different on each platform)

**Comment by rejhgadellaa** [comment]
```
# -*- coding: utf-8 -*-
#!/usr/bin/env python

from __future__ import print_function
import os
import requests
import concurrent.futures


def optimize_jpg(file_path,backup=False):
    if type(file_path)!=str :
        raise Exception("Image file path must be string")
    if type(backup)!=bool:
        raise Exception("Backup must be of type Boolean")

    if not os.path.isfile(os.path.abspath(file_path)) and not os.path.isdir(os.path.abspath(file_path)):
        raise Exception("file path must be a valid directory or a file path "+os.path.abspath(file_path) )

    if os.path.isfile(file_path) and os.path.getsize(file_path)>>20 < 5:
        if backup:
            shutil.copyfile(file_path,file_path.rstrip(".jpg")+".backup.jpg")
        files={'input':open(file_path,'rb')}            
        r=requests.post("http://jpgoptimiser.com/optimise",files=files,stream=True)
        if r.status_code == 200:
            with open(file_path, 'wb') as f:
                    for chunk in r.iter_content(1024):
                            f.write(chunk)

        elif os.path.isdir(file_path):
            for root,dirs,files in os.walk("."):
                for file in files:
                    if file.endswith(".jpg"):
                        optimize_jpg(os.path.abspath(os.path.join(root,file)),backup)

def optimize_png(file_path,backup=False):
    if type(file_path)!=str :
        raise Exception("Image file path must be string")
    if type(backup)!=bool:
        raise Exception("Backup must be of type Boolean")

    if not os.path.isfile(os.path.abspath(file_path)) and not os.path.isdir(os.path.abspath(file_path)):
        raise Exception("file path must be a valid directory or a file path "+os.path.abspath(file_path) )

    if os.path.isfile(file_path) and os.path.getsize(file_path)>>20 < 5:
        if backup:
            shutil.copyfile(file_path,file_path.rstrip(".png")+".backup.png")
        files={'input':open(file_path,'rb')}            
        r=requests.post("http://pngcrush.com/optimise",files=files,stream=True)
        if r.status_code == 200:
            with open(file_path, 'wb') as f:
                for chunk in r.iter_content(1024):
                        f.write(chunk)

        elif os.path.isdir(file_path):
            for root,dirs,files in os.walk("."):
                for file in files:
                    if file.endswith(".png"):
                        optimize_png(os.path.abspath(os.path.join(root,file)),backup)



def optimize(file_path,backup=False):
    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor:
        for root,dirs,files in os.walk(file_path):
            for file in files:
                if file.endswith(".jpg"):
                    executor.submit(optimize_jpg,file_path,backup)
                elif file.endswith(".png"):
                    executor.submit(optimize_png,file_path,backup)
```

**Comment by rejhgadellaa** [comment]
Fixed version above.

**Comment by shantanu561993** [comment]
Thanks @rejhgadellaa ..I'll Upload a new version soon .. and Thanks for using my package in rgpy-web-optimizer . :+1:

**Comment by rejhgadellaa** [comment]
Awesome! Great work on the mod btw!

**Comment by shantanu561993** [comment]
New Version updated .. Thanks .

**Comment by rejhgadellaa** [comment]
My pleasure

**Comment by JimJamUrCode** [comment]
This is still an issue today. I just installed this package and had to manually go through the file and fix indentation issues...
